package tabla_de_simbolos;

import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.FileUtils;

/**
 * 
 * @author DavidCQ
 */
public class GuiRobot extends javax.swing.JFrame {

    Robot robot;
    List<String> listaTexto = null;
    
    /**
     * Creates new form GuiRobot
     */
    public GuiRobot() {
        initComponents();
        robot = new Robot();
        setLocationRelativeTo(null);
    }
    
    public void file2List(File file){
//        System.out.println(file.getPath());
//        System.out.println(file.getAbsolutePath());
        //JOptionPane.showMessageDialog(null, file.getAbsolutePath());

        try {
            listaTexto = FileUtils.readLines(file);
        } catch (IOException ex) {
            listaTexto = null;
            System.out.println(ex.getMessage());
            System.out.println("Fallo al cargar el Archivo");
        }
    }
    
    public static void vaciarTabla(DefaultTableModel tabla){
        for (int c = tabla.getRowCount() - 1; c >= 0; c--) {
            tabla.removeRow(c);
        }
    }
    
    public void llenarTablaCoordenadas(DefaultTableModel tabla, List<String> lista){
        vaciarTabla(tabla);
        int x, y;
        for (String string : lista){
            try {
                x = Integer.parseInt(string.split(",")[0]);
                y = Integer.parseInt(string.split(",")[1]);
                robot.movimiento(string);
                tabla.addRow(new Object[]{x,y});
            }catch(Exception e){
                System.out.println("Malas coordenadas. El formato es x,y");
                return;
            }
        }
    }
    
    public void llenarTablaMovimientos(DefaultTableModel tabla, List<String[]> lista){
        vaciarTabla(tabla);
        for (String[] string : lista){
            try {
                tabla.addRow(new Object[]{string[0],string[1]});
            }catch(Exception e){
                System.out.println("Malas coordenadas. El formato es x,y");
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInterpretar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCoordenadas = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonArchivo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interprete");

        jInterpretar.setText("Interpretar");
        jInterpretar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInterpretarActionPerformed(evt);
            }
        });

        jTableCoordenadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "Y"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableCoordenadas);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movimiento", "Orientación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonArchivo.setText("Seleccionar Archivo");
        jButtonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArchivoActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButtonArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jInterpretar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInterpretar)
                    .addComponent(jButtonArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInterpretarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInterpretarActionPerformed
        if (listaTexto != null && !listaTexto.isEmpty()){
            robot.setListaCoordenadasDadas(listaTexto);
            robot.convertirCoordenadas();
            System.out.println(robot.validarMovimientos());
            robot.mostrarMovimientos();
            
        }else{
            JOptionPane.showMessageDialog(null, "Falta cargar las coordenadas");
        }
//        llenarTablaCoordenadas((DefaultTableModel)jTableCoordenadas.getModel(), listaCoordenadas);
//        llenarTablaMovimientos((DefaultTableModel)jTable1.getModel(), robot.listaMovimientos);
    }//GEN-LAST:event_jInterpretarActionPerformed

    private void jButtonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArchivoActionPerformed
        JFileChooser chooser = new JFileChooser(new File("coordenadas.txt"));
        FileNameExtensionFilter txtfilter = new FileNameExtensionFilter("txt files", "txt");
        chooser.setFileFilter(txtfilter);
//        chooser.setDialogTitle("Open schedule file");
        // set selected filter
        chooser.setFileFilter(txtfilter);
        chooser.showOpenDialog(this);
        if (chooser.getSelectedFile() != null){
            file2List(chooser.getSelectedFile());
        }
        
        if (listaTexto != null){
            StringBuilder aux = new StringBuilder("");
            for (String tmp : listaTexto){
                aux.append(tmp+"\n");
            }
            jTextArea1.setText(aux.toString());
        }
    }//GEN-LAST:event_jButtonArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRobot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRobot().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArchivo;
    private javax.swing.JButton jInterpretar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableCoordenadas;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
